spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/guli_ums?useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: root
    password: 123456
#  profiles:
#    active: dev

mybatis-plus:
  mapper-locations: classpath:/mapper/ums/*.xml
  global-config:
    db-config:
      id-type: auto
  configuration:
# 这个配置会将执行的sql打印出来，在开发或测试的时候可以用
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
